site_name: starstone3's Notebook
site_author: starstone3
site_url: 'https://starstone3.github.io'

repo_name: 'starstone3s repo'
repo_url: 'https://github.com/starstone3/starstone3.github.io'
theme:
  name: material
  language: zh
  icon:
    # logo: material/pac-man
    logo: assets/images/1718441323923.jpg
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      note: fontawesome/solid/pen-nib
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  font:
    text: LXGW WenKai Screen GB Screen # Share Tech
    code: JetBrains Mono
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/link
          name: 关闭自动模式
      - media: "(prefers-color-scheme: light)"
        scheme: default # 日间模式
        primary: yellow # 上方的
        accent: light blue # 链接等可交互元件的高亮色
        toggle:
          icon: material/toggle-switch # 图标
          name: 切换至夜间模式 # 鼠标悬浮提示
      - media: "(prefers-color-scheme: dark)"
        scheme: slate # 夜间模式
        primary: black
        accent: indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: 切换至日间模式
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
nav :
  